use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::{
    AgentThread, AnnotationBatch, ApiError, CatalogQuery, ChangesQuery, CommandAccepted,
    CompleteInitRequest, ConnectionInfo, ContextCatalog, ContextSnapshot, CreateTaskRequest,
    CreateTaskResponse, DiffDocument, DiffQuery, FileContent, FileContentQuery, FilePage,
    FileSearchPage, FileSearchQuery, FileTreeQuery, InitStatus, InteractionResponseRequest,
    ListTasksQuery, PlatformCatalog, PlatformStatus, RegisterInitialWorkspaceRequest,
    RegisterWorkspaceRequest, RegistrationRootPage, RemoveWorkspaceRequest, ReviewSnapshot,
    ReviewSubmissionPage, ReviewSubmissionQuery, ReviewSubmissionResult, SettingsSnapshot,
    StopRunRequest, SubmitRunRequest, SubmitRunResponse, TaskPage, TaskProjection, TaskStreamEvent,
    TaskStreamQuery, TestProviderRequest, TestProviderResult, TimelinePage, TimelineQuery,
    UpdateDefaultTierRequest, UpdateProvidersRequest, UpdateSettingsRequest, WorkspacePage,
};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct WebApiContract {
    pub platform_status: PlatformStatus,
    pub connection_info: ConnectionInfo,
    pub registration_root_page: RegistrationRootPage,
    pub workspace_page: WorkspacePage,
    pub register_workspace: RegisterWorkspaceRequest,
    pub remove_workspace: RemoveWorkspaceRequest,
    pub init_status: InitStatus,
    pub update_providers: UpdateProvidersRequest,
    pub update_default_tier: UpdateDefaultTierRequest,
    pub register_initial_workspace: RegisterInitialWorkspaceRequest,
    pub test_provider: TestProviderRequest,
    pub test_provider_result: TestProviderResult,
    pub complete_init: CompleteInitRequest,
    pub settings: SettingsSnapshot,
    pub update_settings: UpdateSettingsRequest,
    pub platform_catalog: PlatformCatalog,
    pub workspace_catalog: ContextCatalog,
    pub catalog_query: CatalogQuery,
    pub task_page: TaskPage,
    pub list_tasks: ListTasksQuery,
    pub create_task: CreateTaskRequest,
    pub create_task_result: CreateTaskResponse,
    pub task_projection: TaskProjection,
    pub timeline_query: TimelineQuery,
    pub timeline_page: TimelinePage,
    pub submit_run: SubmitRunRequest,
    pub submit_run_result: SubmitRunResponse,
    pub stop_run: StopRunRequest,
    pub interaction_response: InteractionResponseRequest,
    pub command_accepted: CommandAccepted,
    pub task_stream_query: TaskStreamQuery,
    pub task_stream_event: TaskStreamEvent,
    pub context_snapshot: ContextSnapshot,
    pub agent_thread: AgentThread,
    pub review_snapshot: ReviewSnapshot,
    pub file_tree_query: FileTreeQuery,
    pub file_page: FilePage,
    pub file_search_query: FileSearchQuery,
    pub file_search_page: FileSearchPage,
    pub file_content_query: FileContentQuery,
    pub file_content: FileContent,
    pub changes_query: ChangesQuery,
    pub diff_query: DiffQuery,
    pub diff_document: DiffDocument,
    pub annotation_batch: AnnotationBatch,
    pub review_submission_result: ReviewSubmissionResult,
    pub review_submission_query: ReviewSubmissionQuery,
    pub review_submission_page: ReviewSubmissionPage,
    pub api_error: ApiError,
}
